### PR TITLE
Feature/add instrumentation

### PR DESCRIPTION
**Pull request by mgravitt**
Adds instrumentation to the container-- 

See here for dashboard with metrics: https://grafana.digscar.com/d/ZTKjd3aMz/document-cache?orgId=1&from=now-30m&to=now

I will update to the correct branch after the merge

### CODE REVIEW

**Review by sebastianmontero — COMMENTED** [review]
I think it would be best to encapsulate the prometheus functionality in its own class, so as to not to pollute the start script, what do you think?

**Comment by mgravitt** [comment]
> I think it would be best to encapsulate the prometheus functionality in its own class, so as to not to pollute the start script, what do you think?

Yes, for sure. I am not very strong with nodejs. I'm also not sure how the threading works. Do you think it is safe as it is developed (assuming I move prometheus to its own class)?

**Comment by sebastianmontero** [comment]
@dappdever It looks good to me, what are your concerns about threading? Do you want me to move it to its own class?

**Comment by sebastianmontero** [comment]
I've added prometheus encapsulated in its own class.

**Pull request closed without merging**
